-- ════════════════════════════════════════════════════════════════
--  QUOTO — schema Supabase (progetto "quote")
--  Esegui questo script in: Supabase → SQL Editor → New query → Run
-- ════════════════════════════════════════════════════════════════

-- ── Profili utenti (ruolo: admin | collaboratore) ──
create table if not exists quote_utenti (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text,
  nome       text,
  ruolo      text not null default 'collaboratore',  -- 'admin' | 'collaboratore'
  attivo     boolean not null default true,
  creato_da  uuid,
  creato_il  timestamptz not null default now()
);
alter table quote_utenti enable row level security;
drop policy if exists "quote_utenti_select" on quote_utenti;
drop policy if exists "quote_utenti_insert" on quote_utenti;
drop policy if exists "quote_utenti_update" on quote_utenti;
drop policy if exists "quote_utenti_delete" on quote_utenti;
create policy "quote_utenti_select" on quote_utenti for select to authenticated using (true);
create policy "quote_utenti_insert" on quote_utenti for insert to authenticated with check (true);
create policy "quote_utenti_update" on quote_utenti for update to authenticated using (true);
create policy "quote_utenti_delete" on quote_utenti for delete to authenticated using (true);

-- ── Ticket (stato: aperto | in_lavorazione | risolto) ──
create table if not exists quote_ticket (
  id             bigint generated by default as identity primary key,
  titolo         text not null,
  descrizione    text,
  sezione        text default 'Generale',
  priorita       text default 'normale',  -- bassa | normale | alta | urgente
  stato          text default 'aperto',   -- aperto | in_lavorazione | risolto
  segnalato_da   uuid,
  segnalato_nome text,
  risolto_da     uuid,
  risolto_nome   text,
  creato_il      timestamptz not null default now(),
  aggiornato_il  timestamptz,
  risolto_il     timestamptz
);
alter table quote_ticket enable row level security;
drop policy if exists "quote_ticket_select" on quote_ticket;
drop policy if exists "quote_ticket_insert" on quote_ticket;
drop policy if exists "quote_ticket_update" on quote_ticket;
drop policy if exists "quote_ticket_delete" on quote_ticket;
create policy "quote_ticket_select" on quote_ticket for select to authenticated using (true);
create policy "quote_ticket_insert" on quote_ticket for insert to authenticated with check (true);
create policy "quote_ticket_update" on quote_ticket for update to authenticated using (true);
create policy "quote_ticket_delete" on quote_ticket for delete to authenticated using (true);
