-- ════════════════════════════════════════════════════════════════
--  QUOTO — schema Supabase (progetto "quote")
--  Esegui questo script in: Supabase → SQL Editor → New query → Run
-- ════════════════════════════════════════════════════════════════

-- ── Profili utenti (ruolo: admin | collaboratore) ──
create table if not exists quote_utenti (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text,
  nome       text,
  ruolo      text not null default 'collaboratore',  -- 'admin' | 'collaboratore'
  attivo     boolean not null default true,
  creato_da  uuid,
  creato_il  timestamptz not null default now()
);
alter table quote_utenti enable row level security;
drop policy if exists "quote_utenti_select" on quote_utenti;
drop policy if exists "quote_utenti_insert" on quote_utenti;
drop policy if exists "quote_utenti_update" on quote_utenti;
drop policy if exists "quote_utenti_delete" on quote_utenti;
create policy "quote_utenti_select" on quote_utenti for select to authenticated using (true);
create policy "quote_utenti_insert" on quote_utenti for insert to authenticated with check (true);
create policy "quote_utenti_update" on quote_utenti for update to authenticated using (true);
create policy "quote_utenti_delete" on quote_utenti for delete to authenticated using (true);

-- ── Ticket (stato: aperto | in_lavorazione | risolto) ──
create table if not exists quote_ticket (
  id             bigint generated by default as identity primary key,
  titolo         text not null,
  descrizione    text,
  sezione        text default 'Generale',
  priorita       text default 'normale',  -- bassa | normale | alta | urgente
  stato          text default 'aperto',   -- aperto | in_lavorazione | risolto
  segnalato_da   uuid,
  segnalato_nome text,
  risolto_da     uuid,
  risolto_nome   text,
  creato_il      timestamptz not null default now(),
  aggiornato_il  timestamptz,
  risolto_il     timestamptz
);
alter table quote_ticket enable row level security;
drop policy if exists "quote_ticket_select" on quote_ticket;
drop policy if exists "quote_ticket_insert" on quote_ticket;
drop policy if exists "quote_ticket_update" on quote_ticket;
drop policy if exists "quote_ticket_delete" on quote_ticket;
create policy "quote_ticket_select" on quote_ticket for select to authenticated using (true);
create policy "quote_ticket_insert" on quote_ticket for insert to authenticated with check (true);
create policy "quote_ticket_update" on quote_ticket for update to authenticated using (true);
create policy "quote_ticket_delete" on quote_ticket for delete to authenticated using (true);

-- ── Permessi preventivatori per utente (null = tutti) ──
alter table quote_utenti add column if not exists moduli text[];
-- ── Rete / sottorete del collaboratore ──
alter table quote_utenti add column if not exists rete text;

-- ── Anagrafiche clienti (modello Assieasy: fisica/giuridica) ──
create table if not exists quote_anagrafiche (
  id              uuid primary key default gen_random_uuid(),
  tipo            text not null default 'fisica',  -- fisica | giuridica
  nominativo      text not null,                   -- "COGNOME NOME" o ragione sociale
  cognome         text,
  nome            text,
  ragione_sociale text,
  codice_fiscale  text,
  partita_iva     text,
  tipo_societa    text,
  professione     text,
  stato_civile    text,
  data_nascita    date,
  indirizzo text, civico text, cap text, comune text, provincia text, nazione text default 'Italia',
  telefono text, cellulare text, email text, pec text,
  note            text,
  creato_da       uuid,
  creato_il       timestamptz not null default now()
);
alter table quote_anagrafiche enable row level security;
drop policy if exists "quote_anag_select" on quote_anagrafiche;
drop policy if exists "quote_anag_insert" on quote_anagrafiche;
drop policy if exists "quote_anag_update" on quote_anagrafiche;
drop policy if exists "quote_anag_delete" on quote_anagrafiche;
create policy "quote_anag_select" on quote_anagrafiche for select to authenticated using (true);
create policy "quote_anag_insert" on quote_anagrafiche for insert to authenticated with check (true);
create policy "quote_anag_update" on quote_anagrafiche for update to authenticated using (true);
create policy "quote_anag_delete" on quote_anagrafiche for delete to authenticated using (true);
create index if not exists idx_anag_nominativo on quote_anagrafiche (nominativo);
create index if not exists idx_anag_cf on quote_anagrafiche (codice_fiscale);

-- ── Preventivi (per storico + performance preventivi/polizze) ──
create table if not exists quote_preventivi (
  id             uuid primary key default gen_random_uuid(),
  modulo         text,            -- persona | tutela | rca ...
  prodotto       text,            -- 'Infortuni Individuale', 'Tutela Legale — Circolazione' ...
  compagnia      text,
  premio         numeric(10,2),
  cliente        text,
  dati           jsonb,
  polizza_emessa boolean not null default false,
  polizza_il     timestamptz,
  creato_da      uuid,
  creato_nome    text,
  creato_il      timestamptz not null default now()
);
alter table quote_preventivi enable row level security;
drop policy if exists "quote_prev_select" on quote_preventivi;
drop policy if exists "quote_prev_insert" on quote_preventivi;
drop policy if exists "quote_prev_update" on quote_preventivi;
drop policy if exists "quote_prev_delete" on quote_preventivi;
create policy "quote_prev_select" on quote_preventivi for select to authenticated using (true);
create policy "quote_prev_insert" on quote_preventivi for insert to authenticated with check (true);
create policy "quote_prev_update" on quote_preventivi for update to authenticated using (true);
create policy "quote_prev_delete" on quote_preventivi for delete to authenticated using (true);
create index if not exists idx_prev_creato_da on quote_preventivi (creato_da);
create index if not exists idx_prev_creato_il on quote_preventivi (creato_il);
